{
    "name": "Restaurant Pilot",
    "version": "17.0.3.0.0",
    "category": "Point of Sale",
    "summary": "Backoffice simplifie pour gerer les restaurants, utilisateurs, ventes et stocks.",
    "author": "Local",
    "license": "LGPL-3",
    "depends": [
        "account",
        "barcodes",
        "mrp",
        "point_of_sale",
        "pos_hr",
        "pos_restaurant",
        "purchase",
        "sale_management",
        "stock",
        "web",
    ],
    "data": [
        "security/resto_groups.xml",
        "security/ir.model.access.csv",
        "data/restaurants.xml",
        "data/product_categories.xml",
        "data/products.xml",
        "views/restaurant_views.xml",
        "views/user_views.xml",
        "views/audit_views.xml",
        "views/dashboard_templates.xml",
        "views/menu_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "restaurant_starter/static/src/js/dashboard_action.js",
        ],
    },
    "installable": True,
    "application": True,
}
